### ISSUE TITLE
直接运行报错

### ISSUE THREAD

**Issue by wuzuowuyou** [zheng-yuwei/multi-label-classification#3]
File "run.py", line 106, in run
    classifier = MultiLabelClassifier()
  File "/data_2/everyday/0323/face/multi-label-classification-master/multi_label/trainer.py", line 95, in __init__
    optimizer = RAdam(lr=1e-3)
  File "/data_2/everyday/0323/face/multi-label-classification-master/utils/radam.py", line 42, in __init__
    super(RAdam, self).__init__(**kwargs)
TypeError: __init__() missing 1 required positional argument: 'name'

不知道是不是哪个库版本问题

**Comment by wuzuowuyou** [comment]
测试的时候也报错

Deprecated in favor of operator or tf.math.divide.
2020-03-24 12:43:41,388 file_util.py:102 INFO 4. 完成tf.data (image, label, path) 测试数据集构造；
2020-03-24 12:43:41,407 file_util.py:111 INFO 5. 构造tf.data多epoch训练模式；
Traceback (most recent call last):
  File "/data_2/everyday/0323/face/multi-label-classification-master/run.py", line 214, in <module>
    run()
  File "/data_2/everyday/0323/face/multi-label-classification-master/run.py", line 122, in run
    total_test, wrong_count, great_total_count, great_wrong_count, great_wrong_records = test_model(classifier)
  File "/data_2/everyday/0323/face/multi-label-classification-master/run.py", line 176, in test_model
    results = classifier.predict(np.array(images))
  File "/data_2/everyday/0323/face/multi-label-classification-master/multi_label/trainer.py", line 203, in predict
    predictions = self.model.predict(test_images)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 908, in predict
    use_multiprocessing=use_multiprocessing)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 477, in predict
    workers=workers, use_multiprocessing=use_multiprocessing, **kwargs)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 454, in _model_iteration
    total_epochs=1)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 123, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 86, in execution_function
    distributed_function(input_fn))
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 449, in __call__
    self._initialize(args, kwds, add_initializers_to=initializer_map)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 392, in _initialize
    *args, **kwds))
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1847, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2147, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2038, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 335, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 73, in distributed_function
    per_replica_function, args=(x, y, sample_weights))
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 764, in experimental_run_v2
    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 1810, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 2155, in _call_for_each_replica
    return fn(*args, **kwargs)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 292, in wrapper
    return func(*args, **kwargs)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 162, in _predict_on_batch
    return predict_on_batch(model, x)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 370, in predict_on_batch
    return model(inputs)  # pylint: disable=not-callable
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 821, in __call__
    with graph.as_default(), backend.name_scope(self._name_scope()):
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 760, in name_scope
    return ops.name_scope_v2(name)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 6419, in __init__
    raise ValueError("name for name_scope must be a string.")
ValueError: name for name_scope must be a string.

**Comment by zheng-yuwei** [comment]
> File "run.py", line 106, in run
> classifier = MultiLabelClassifier()
> File "/data_2/everyday/0323/face/multi-label-classification-master/multi_label/trainer.py", line 95, in **init**
> optimizer = RAdam(lr=1e-3)
> File "/data_2/everyday/0323/face/multi-label-classification-master/utils/radam.py", line 42, in **init**
> super(RAdam, self).**init**(**kwargs)
> TypeError: **init**() missing 1 required positional argument: 'name'
> 
> 不知道是不是哪个库版本问题

这个是TensorFlow版本问题，你可以安装他提示的在multi-label-classification-master/utils/radam.py中给init()加上name参数，或者不适用RAdam优化器，用Adam之类的优化器也行。话说我已经弃坑tensorflow玩pytorch了。。。TensorFlow太乱了

**Comment by zheng-yuwei** [comment]
> 测试的时候也报错
> 
> Deprecated in favor of operator or tf.math.divide.
> 2020-03-24 12:43:41,388 file_util.py:102 INFO 4. 完成tf.data (image, label, path) 测试数据集构造；
> 2020-03-24 12:43:41,407 file_util.py:111 INFO 5. 构造tf.data多epoch训练模式；
> Traceback (most recent call last):
> File "/data_2/everyday/0323/face/multi-label-classification-master/run.py", line 214, in
> run()
> File "/data_2/everyday/0323/face/multi-label-classification-master/run.py", line 122, in run
> total_test, wrong_count, great_total_count, great_wrong_count, great_wrong_records = test_model(classifier)
> File "/data_2/everyday/0323/face/multi-label-classification-master/run.py", line 176, in test_model
> results = classifier.predict(np.array(images))
> File "/data_2/everyday/0323/face/multi-label-classification-master/multi_label/trainer.py", line 203, in predict
> predictions = self.model.predict(test_images)
> File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 908, in predict
> use_multiprocessing=use_multiprocessing)
> File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 477, in predict
> workers=workers, use_multiprocessing=use_multiprocessing, **kwargs)
> File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 454, in _model_iteration
> total_epochs=1)
> File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 123, in run_one_epoch
> batch_outs = execution_function(iterator)
> File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 86, in execution_function
> distributed_function(input_fn))
> File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 449, in **call**
> self._initialize(args, kwds, add_initializers_to=initializer_map)
> File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 392, in _initialize
> *args, **kwds))
> File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1847, in _get_concrete_function_internal_garbage_collected
> graph_function, _, _ = self._maybe_define_function(args, kwargs)
> File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2147, in _maybe_define_function
> graph_function = self._create_graph_function(args, kwargs)
> File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2038, in _create_graph_function
> capture_by_value=self._capture_by_value),
> File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 915, in func_graph_from_py_func
> func_outputs = python_func(*func_args, **func_kwargs)
> File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 335, in wrapped_fn
> return weak_wrapped_fn().**wrapped**(*args, **kwds)
> File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 73, in distributed_function
> per_replica_function, args=(x, y, sample_weights))
> File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 764, in experimental_run_v2
> return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
> File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 1810, in call_for_each_replica
> return self._call_for_each_replica(fn, args, kwargs)
> File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 2155, in _call_for_each_replica
> return fn(*args, **kwargs)
> File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 292, in wrapper
> return func(*args, **kwargs)
> File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 162, in _predict_on_batch
> return predict_on_batch(model, x)
> File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 370, in predict_on_batch
> return model(inputs) # pylint: disable=not-callable
> File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 821, in **call**
> with graph.as_default(), backend.name_scope(self._name_scope()):
> File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 760, in name_scope
> return ops.name_scope_v2(name)
> File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 6419, in **init**
> raise ValueError("name for name_scope must be a string.")
> ValueError: name for name_scope must be a string.

感觉是name_scope的问题

**Comment by zheng-yuwei** [comment]
版本不对
