### ISSUE TITLE
BACKBONE_MIXNET_18

### ISSUE THREAD

**Issue by wuzuowuyou** [zheng-yuwei/multi-label-classification#4]
可以训练，但是跑预测的时候报错。。。不知道哪里形状对不上了，跑这个也是 ResNeXt18
下面的log是BACKBONE_MIXNET_18

Deprecated in favor of operator or tf.math.divide.
2020-03-25 10:22:54,336 file_util.py:102 INFO 4. 完成tf.data (image, label, path) 测试数据集构造；
2020-03-25 10:22:54,353 file_util.py:111 INFO 5. 构造tf.data多epoch训练模式；
2020-03-25 10:22:54.692572: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 153600000 exceeds 10% of system memory.
2020-03-25 10:22:55.040592: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 153600000 exceeds 10% of system memory.
Traceback (most recent call last):
  File "run.py", line 214, in <module>
    run()
  File "run.py", line 122, in run
    total_test, wrong_count, great_total_count, great_wrong_count, great_wrong_records = test_model(classifier)
  File "run.py", line 176, in test_model
    results = classifier.predict(np.array(images))
  File "/data_2/everyday/0323/face/multi-label-2/multi-label-classification-master/multi_label/trainer.py", line 203, in predict
    predictions = self.model.predict(test_images)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 908, in predict
    use_multiprocessing=use_multiprocessing)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 477, in predict
    workers=workers, use_multiprocessing=use_multiprocessing, **kwargs)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 454, in _model_iteration
    total_epochs=1)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 123, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 86, in execution_function
    distributed_function(input_fn))
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 449, in __call__
    self._initialize(args, kwds, add_initializers_to=initializer_map)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 392, in _initialize
    *args, **kwds))
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1847, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2147, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2038, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 335, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 73, in distributed_function
    per_replica_function, args=(x, y, sample_weights))
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 764, in experimental_run_v2
    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 1810, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 2155, in _call_for_each_replica
    return fn(*args, **kwargs)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 292, in wrapper
    return func(*args, **kwargs)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 162, in _predict_on_batch
    return predict_on_batch(model, x)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 370, in predict_on_batch
    return model(inputs)  # pylint: disable=not-callable
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 854, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 695, in call
    return self._run_internal_graph(inputs, training=training, mask=mask)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 844, in _run_internal_graph
    output_tensors = layer(computed_tensors, **kwargs)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 819, in __call__
    self.name)
  File "/data_1/Yang/software_install/Anaconda1105/envs/tf_1.15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/input_spec.py", line 213, in assert_input_compatibility
    ' but received input with shape ' + str(shape))
ValueError: Input 0 of layer depthwise_conv2d_1 is incompatible with the layer: expected axis 3 of input shape to have value 16 but received input with shape [None, 40, 40, 8]

**Comment by zheng-yuwei** [comment]
debug吧，你这个应该是哪个分组的channel数搞错了

**Comment by wuzuowuyou** [comment]
训练可以训练，测试也用的训练的数据集。我就奇怪了呢，训练可以跑，测试就报哪里维度不匹配。
一定是测试与训练的时候哪里不一样。果真：
在run.py的开头 我的是tf1.15版本
if FLAGS.mode == 'test':
    tf.enable_eager_execution()
会报错 “RuntimeError: __iter__() is only supported inside of tf.function or when eager execution is enabled”

然后我用opencv读取图片调用
results = classifier.predict(np.array(images))
就可以。。
哎，实在不知道怎么改了，不知道tf1.15与1.13这方面的差异了。

还有，
    BACKBONE_RESNET_18 = 'resnet-18'
    BACKBONE_RESNET_18_V2 = 'resnet-18-v2'
    BACKBONE_RESNEXT_18 = 'resnext-18'
    BACKBONE_MIXNET_18 = 'mixnet-18'
    BACKBONE_MOBILENET_V2 = 'mobilenet-v2'
这些模型与loss与优化器哪个组合最好啊，
谢谢您能回复我一下

**Comment by zheng-yuwei** [comment]
resnext-18最好，但是训练速度慢，我自己用的resnet-18，因为训练速度快，可以快速实验和调参
